---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: root-ssh-keys
  namespace: default
spec:
  encryptedData:
    privateKey: AgCStOakszZlBXf1yhakyt1uc8XMSS9RkiZ30IMD2OiQrTrjvRvAgQlrveMtr/59E+OcfL3qyuMt8RSUYlIGHYoG3wz9z/vOrSzs95q5zmfOKCl03b53rqU71R5N4KTzWoFbHP6UV6jAiTZ9NxriNwJzz8YogdIEMk1YbDKFmJ+p5zzz2+fUWFMTQomdvDnz3Ikvl57UH6PJ3Vcgof/Wtp+4veZXJ0ksmxmF3y6pCzRI74+e9+a19AwnWo/1AmyOddxurH5ygTRJQsJfm9EWadqElcPh8nEJIDIBd3z0oEsI7DOx/tfTDDU8Nd8dXkjH7iP3pC766uNycCzpfNm0oVq2QZupBxLHy0l8L93Nn+b0/OGuXAky0PaEhJqSWHaC+gEiLS0C+JXUuyMzjF7PMD7/C49QHXbTTpGucd+NW0GmGJ7G74wWS1kLe3kMF8xRwB3fgZG//hPgNfSlLYFKH1MS+ZTwO2f5IvXkHZXLx5eeRBhIIruiZFc+xZolBfwjeCvI+UmO3Oy3NmIzL0gfAJQmlwU9U7eJGFqKs7/6s2r5NNZmm7AmpKPB7A8b3izygg13PBcq/VkJQpt3amEJNsVBqUtpHRfIjKo+uzgRG+H7MPVAq5Tf7+uq+9mdY424c87WJUAmB3R2apew2ASo6UkCz3iFbAVh0U3cUEhsacAzBkm5L/dMP1a4mNqMTHNGYUv/ZikChDhHLyl6Xw==
    publicKey: AgCWnC46sw0TXeHGnodt953XwkJbEK95EaW4beGeIk71Uw9/vDngqh/g9ELakn+NFkB+R4JBMqhLE40kIHJ2tMKg0dy16SPpMHfL2GZrhtc3OSCidMlGv5nFyVSM78q8GAy533tSnyoNyxsE4VWmmx4RWAnxBEkR3jJvUPLqz1dye/9XWkGOLh2kcfmJ7OvSpa7GNAJ2LEZaXZxr5XAHVhm581TpCYUE5jeAd13JiESRBp93tEeXpuoMxGnRemIKnTetwduul84xxuY78QIOk7mDIEKb1xLgSqQ6DcbE0fhc/DydZp0OG1TCW3zalzvzRqbGbUkyoMt4CTX7r1clrx80OkIC3r6VTl8G7cPzO/xSBLGEecgZEW9LGtub1sV7JIqRGkxO5vvvVww6bnqPC2sgnyfyen45WEenZOCLB4mQQ3xV/yTe0IF1BNrJmETX5d1B13dG3FE+l8IcxZStjnN94VMzmkofgLPk3OFvJ8m8MYYLz3o9WSI49CY1Dj87HtvR36jP2Jul9CseY2Adg6sNJBsCszFZ6jcbIFEGpVeMzVc8fUxR5L/x/Ba4pCivZ978hkVhRFo4Tym+mmzln5CKrtetCjrTTVbD80IjCdTN6/Fxdq4z0OUYYHojLCyQt75yt/3ptmbD/dOoGrWRgYtiCSPTSef6PTVVXfJacahhAOxibxXo81wG94821U2d5h5LFbY8b5e6gWXE8A==
  template:
    metadata:
      creationTimestamp: null
      name: root-ssh-keys
      namespace: default
    type: Opaque
