name: Run script hello.py on push
on:
  push:
    branches:
    - master
jobs:
  prepare:
    #runs-on: [my_runner]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
      - name: Start script hello.py
        run: python3 hello.py
