name: Basic calc test
on:
  push:
    branches:
    - master
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'

      - name: Run test
        run: python3 testBasicCalc.py