apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smee-client
  template:
    metadata:
      labels:
        app: smee-client
    spec:
      containers:
        - name: smee-client
          image: node:18-alpine
          command: ["/bin/sh", "-c"]
          args:
            - "npm install -g smee-client && smee --url https://smee.io/tl6wn7TWXclsQRZ --target http://jenkins.ci-cd-helm.svc.cluster.local:8080/github-webhook/ --path /github-webhook/ --port 3000"
          env:
            - name: SMEE_URL
              value: "https://smee.io/tl6wn7TWXclsQRZ"
            - name: JENKINS_WEBHOOK
              value: "http://jenkins.ci-cd-helm.svc.cluster.local:8080/github-webhook/"
