apiVersion: v1
kind: Namespace
metadata:
  name: web-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: web-test
data:
  dummy: "placeholder"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: web-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      volumes:
        - name: web-root
          emptyDir: {}
        - name: ssh-keys
          secret:
            secretName: nginx-ssh-secret
            defaultMode: 0600
      initContainers:
        - name: init-index
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -eu
              HOST="$(hostname)"
              echo "<!doctype html><html><head><meta charset='utf-8'><title>${HOST}</title></head><body><h1>${HOST}</h1></body></html>" > /workdir/index.html
          volumeMounts:
            - name: web-root
              mountPath: /workdir
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-root
              mountPath: /usr/share/nginx/html
            - name: ssh-keys
              mountPath: /root/.ssh
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
  namespace: web-test
spec:
  selector:
    app: nginx-test
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
  namespace: web-test
spec:
  rules:
    - host: nginx-test.k8s-5.sa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-test-svc
                port:
                  number: 80
