apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
spec:
  containers:
  - name: failing-container
    image: busybox
    command: ["sh", "-c"]
    args: ["echo 'This pod will fail immediately'; exit 1"]
  restartPolicy: Never
