apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-app
  labels:
    app: logging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-app
  template:
    metadata:
      labels:
        app: logging-app
    spec:
      containers:
      - name: logger-container
        image: busybox
        command: ["sh", "-c"]
        args: ["counter=0; while true; do echo \"Timestamp: $(date) - Counter: $counter\"; counter=$((counter+1)); sleep 5; done"]
