apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: master
      port: {{ .Values.service.ports.master }}
      targetPort: {{ .Values.service.ports.master }}     
    - name: slave
      port: {{ .Values.service.ports.slave }}
      targetPort: {{ .Values.service.ports.slave }}     
  selector:
    app: {{ include "jenkins.fullname" . }}
