name: Docker Build and Push with Email

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-app:latest
            ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-app:${{ github.sha }}

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Docker build ${{ job.status }} for ${{ github.repository }}"
          to: ${{ secrets.MAIL_TO }}
          from: "CI Bot <${{ secrets.SMTP_USERNAME }}>"
          body: |
            Build status: ${{ job.status }}
            Repo: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Image:
              ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-app:latest
              ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-app:${{ github.sha }}
            Workflow: ${{ github.workflow }}
            Branch: ${{ github.ref_name }}
