---
name: Docker Build & Push with Telegram

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/flask-app:latest
            ghcr.io/${{ env.OWNER_LC }}/flask-app:${{ github.sha }}

      - name: Send Telegram notification
        if: always()
        run: |
          STATUS=${{ job.status }}
          MESSAGE="Docker build $STATUS
          Repo: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Image:
            ghcr.io/${{ secrets.GHCR_USERNAME }}/flask-app:${{ github.sha }}
          Branch: ${{ github.ref_name }}"
          curl -s -X POST \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE"
