apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-server
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 31003  # можно выбрать любой свободный в диапазоне 30000-32767
