apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: {{ .Values.namespace }}
data:
  jenkins.yaml: |
    jenkins:
      numExecutors: 2
      clouds:
      - kubernetes:
          containerCapStr: "10"
          maxRequestsPerHostStr: "32"
          jenkinsUrl: "http://jenkins:8080"
          name: "kubernetes"
          namespace: "{{ .Values.namespace }}"
          skipTlsVerify: true
    credentials:
      system:
        domainCredentials:
        - credentials:
          - usernamePassword:
              description: "Githubuser"
              id: "some_randome"
              password: "{{ .Values.jenkins.github.password }}"
              scope: GLOBAL
              username: "{{ .Values.jenkins.github.username }}"
    unclassified:
      location:
        adminAddress: "{{ .Values.jenkins.adminEmail }}"
        url: "http://{{ .Values.jenkins.ingress.host }}/"
      shell:
        shell: "/bin/bash"
