apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html.template: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Pod Info</title>
    </head>
    <body>
        <h1>Hostname: HOSTNAME_PLACEHOLDER</h1>
    </body>
    </html>